[[redirects]]
  from = "/ai-agents"
  to = "/redirect.html?project=ai-agents"
  status = 200

[[redirects]]
  from = "/stock-picker"
  to = "/redirect.html?project=stock-picker"
  status = 200

[[redirects]]
  from = "/ai-coder"
  to = "/redirect.html?project=ai-coder"
  status = 200

[[redirects]]
  from = "/career-conversation"
  to = "/redirect.html?project=career-conversation"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
